In [1]:
import pandas as pd

In [2]:
food=pd.read_csv (r"C:\Users\anany\Downloads\foods.csv")

In [3]:
food

    First Name  Gender          City Frequency       Item  Spend
0        Wanda  Female      Stamford    Weekly     Burger  15.66
1         Eric    Male      Stamford     Daily    Chalupa  10.56
2      Charles    Male      New York     Never      Sushi  42.14
3         Anna  Female  Philadelphia      Once  Ice Cream  11.01
4      Deborah  Female  Philadelphia     Daily    Chalupa  23.49
..         ...     ...           ...       ...        ...    ...
995      Donna  Female      New York   Monthly      Sushi  83.53
996     Albert    Male  Philadelphia     Daily      Sushi  72.88
997       Jean  Female      Stamford    Weekly      Donut   5.85
998    Jessica  Female      New York     Daily    Chalupa  43.19
999      Brian    Male      New York     Daily    Chalupa  28.36

[1000 rows x 6 columns]

In [4]:
week2=pd.read_csv (r"C:\Users\anany\Downloads\restaurant_week_2_sales.csv")

In [5]:
week2

     Customer ID  Food ID
0            688       10
1            813        7
2            495       10
3            189        5
4            267        3
..           ...      ...
245          783       10
246          556       10
247          547        9
248          252        9
249          249        6

[250 rows x 2 columns]

In [7]:
week1sales= pd.read_csv(r"C:\Users\anany\Downloads\restaurant_week_1_sales.csv")

In [8]:
week1sales

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

In [9]:
week1=pd.read_csv(r"C:\Users\anany\Downloads\restaurant_week_1_times.csv")

In [10]:
week1

    Time of Day
0      14:54:59
1      20:55:17
2      01:16:22
3      16:17:26
4      19:26:11
..          ...
245    04:44:14
246    07:46:21
247    20:45:08
248    01:09:06
249    18:18:50

[250 rows x 1 columns]

In [11]:
pd.concat([week1,week2])

    Time of Day  Customer ID  Food ID
0      14:54:59          NaN      NaN
1      20:55:17          NaN      NaN
2      01:16:22          NaN      NaN
3      16:17:26          NaN      NaN
4      19:26:11          NaN      NaN
..          ...          ...      ...
245         NaN        783.0     10.0
246         NaN        556.0     10.0
247         NaN        547.0      9.0
248         NaN        252.0      9.0
249         NaN        249.0      6.0

[500 rows x 3 columns]

In [12]:
pd.concat([week1,week2],ignore_index=False)

    Time of Day  Customer ID  Food ID
0      14:54:59          NaN      NaN
1      20:55:17          NaN      NaN
2      01:16:22          NaN      NaN
3      16:17:26          NaN      NaN
4      19:26:11          NaN      NaN
..          ...          ...      ...
245         NaN        783.0     10.0
246         NaN        556.0     10.0
247         NaN        547.0      9.0
248         NaN        252.0      9.0
249         NaN        249.0      6.0

[500 rows x 3 columns]

In [13]:
pd.concat([week1,week2],ignore_index=True)

    Time of Day  Customer ID  Food ID
0      14:54:59          NaN      NaN
1      20:55:17          NaN      NaN
2      01:16:22          NaN      NaN
3      16:17:26          NaN      NaN
4      19:26:11          NaN      NaN
..          ...          ...      ...
495         NaN        783.0     10.0
496         NaN        556.0     10.0
497         NaN        547.0      9.0
498         NaN        252.0      9.0
499         NaN        249.0      6.0

[500 rows x 3 columns]

In [15]:
df1=pd.DataFrame([28,10,3],columns=['A'])
df1

    A
0  28
1  10
2   3

In [16]:
df2=pd.DataFrame([13,17,8],columns=['B']) 
df2

    B
0  13
1  17
2   8

In [17]:
pd.concat([df1,df2])

      A     B
0  28.0   NaN
1  10.0   NaN
2   3.0   NaN
0   NaN  13.0
1   NaN  17.0
2   NaN   8.0

In [18]:
pd.concat([df1,df2],axis="index")

      A     B
0  28.0   NaN
1  10.0   NaN
2   3.0   NaN
0   NaN  13.0
1   NaN  17.0
2   NaN   8.0

In [19]:
pd.concat([df1,df2],axis="columns")

    A   B
0  28  13
1  10  17
2   3   8

In [20]:
food.head(5)

  First Name  Gender          City Frequency       Item  Spend
0      Wanda  Female      Stamford    Weekly     Burger  15.66
1       Eric    Male      Stamford     Daily    Chalupa  10.56
2    Charles    Male      New York     Never      Sushi  42.14
3       Anna  Female  Philadelphia      Once  Ice Cream  11.01
4    Deborah  Female  Philadelphia     Daily    Chalupa  23.49

In [3]:
import pandas as pd

In [4]:
customer=pd.read_csv (r"C:\Users\anany\Downloads\restaurant_customers.csv")

In [5]:
customer.head()

   ID First Name Last Name  Gender  Company                     Occupation
0   1     Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
1   2   Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
2   3      Roger     Black    Male  Tagfeed              Account Executive
3   4     Steven     Evans    Male     Fatz               Registered Nurse
4   5       Judy  Morrison  Female  Demivee                Legal Assistant