In [45]:
import pandas as pd

In [46]:
food=pd.read_csv (r"C:\Users\anany\Downloads\foods.csv")

In [47]:
food

    First Name  Gender          City Frequency       Item  Spend
0        Wanda  Female      Stamford    Weekly     Burger  15.66
1         Eric    Male      Stamford     Daily    Chalupa  10.56
2      Charles    Male      New York     Never      Sushi  42.14
3         Anna  Female  Philadelphia      Once  Ice Cream  11.01
4      Deborah  Female  Philadelphia     Daily    Chalupa  23.49
..         ...     ...           ...       ...        ...    ...
995      Donna  Female      New York   Monthly      Sushi  83.53
996     Albert    Male  Philadelphia     Daily      Sushi  72.88
997       Jean  Female      Stamford    Weekly      Donut   5.85
998    Jessica  Female      New York     Daily    Chalupa  43.19
999      Brian    Male      New York     Daily    Chalupa  28.36

[1000 rows x 6 columns]

In [48]:
week2=pd.read_csv (r"C:\Users\anany\Downloads\restaurant_week_2_sales.csv")

In [49]:
week2

     Customer ID  Food ID
0            688       10
1            813        7
2            495       10
3            189        5
4            267        3
..           ...      ...
245          783       10
246          556       10
247          547        9
248          252        9
249          249        6

[250 rows x 2 columns]

In [50]:
week1sales= pd.read_csv(r"C:\Users\anany\Downloads\restaurant_week_1_sales.csv")

In [51]:
week1sales

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

In [52]:
week1=pd.read_csv(r"C:\Users\anany\Downloads\restaurant_week_1_times.csv")

In [53]:
week1

    Time of Day
0      14:54:59
1      20:55:17
2      01:16:22
3      16:17:26
4      19:26:11
..          ...
245    04:44:14
246    07:46:21
247    20:45:08
248    01:09:06
249    18:18:50

[250 rows x 1 columns]

In [54]:
customer=pd.read_csv (r"C:\Users\anany\Downloads\restaurant_customers.csv")

In [55]:
customer

,ID,First Name,Last Name,Gender,Company,Occupation
0,1,Joseph,Perkins,Male,Dynazzy,Community Outreach Specialist
1,2,Jennifer,Alvarez,Female,DabZ,Senior Quality Engineer
2,3,Roger,Black,Male,Tagfeed,Account Executive
3,4,Steven,Evans,Male,Fatz,Registered Nurse
4,5,Judy,Morrison,Female,Demivee,Legal Assistant
...,...,...,...,...,...,...
995,996,Debra,Garcia,Female,Dazzlesphere,Structural Engineer
996,997,Douglas,Bishop,Male,Livepath,Developer I
997,998,Frank,Franklin,Male,Brainverse,Nurse Practicioner
998,999,Jessica,Burns,Female,Babbleblab,Financial Advisor
999,1000,Brian,Daniels,Male,Tazzy,Physical Therapy Assistant

In [56]:
week2.merge(customer,how="left",left_on="Customer ID", right_on="ID")

,Customer ID,Food ID,ID,First Name,Last Name,Gender,Company,Occupation
0,688,10,688,Carl,Williamson,Male,Thoughtmix,Graphic Designer
1,813,7,813,Johnny,Walker,Male,Kayveo,Developer II
2,495,10,495,Deborah,Little,Female,Babbleblab,VP Accounting
3,189,5,189,Roger,Gordon,Male,Skilith,Operator
4,267,3,267,Matthew,Wood,Male,Agimba,Product Engineer
...,...,...,...,...,...,...,...,...
245,783,10,783,Phyllis,Meyer,Female,Voolia,Information Systems Manager
246,556,10,556,Samuel,Bailey,Male,Oyoloo,Nurse
247,547,9,547,Tina,Watkins,Female,Thoughtstorm,Accountant II
248,252,9,252,Douglas,Powell,Male,Jetwire,Geologist IV
249,249,6,249,Anthony,Carpenter,Male,Shuffletag,Health Coach I

In [57]:
week2.merge(customer,how="left",left_on="Customer ID", right_on="ID").drop("ID",axis="columns")

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation
0,688,10,Carl,Williamson,Male,Thoughtmix,Graphic Designer
1,813,7,Johnny,Walker,Male,Kayveo,Developer II
2,495,10,Deborah,Little,Female,Babbleblab,VP Accounting
3,189,5,Roger,Gordon,Male,Skilith,Operator
4,267,3,Matthew,Wood,Male,Agimba,Product Engineer
...,...,...,...,...,...,...,...
245,783,10,Phyllis,Meyer,Female,Voolia,Information Systems Manager
246,556,10,Samuel,Bailey,Male,Oyoloo,Nurse
247,547,9,Tina,Watkins,Female,Thoughtstorm,Accountant II
248,252,9,Douglas,Powell,Male,Jetwire,Geologist IV
249,249,6,Anthony,Carpenter,Male,Shuffletag,Health Coach I

In [58]:
week1sales.merge(week2,how="inner",on="Customer ID",suffixes=["-week1","week2"])

    Customer ID  Food ID-week1  Food IDweek2
0           537              9             5
1           155              9             3
2           503              5             8
3           503              5             9
4           155              1             3
..          ...            ...           ...
57          945              5             4
58          343              3             5
59          343              3             2
60          343              3             7
61          621              9             6

[62 rows x 3 columns]

In [59]:
week1sales[week1sales["Customer ID"] == 155]

    Customer ID  Food ID
4           155        9
17          155        1

In [60]:
week2[week2["Customer ID"] == 155]

     Customer ID  Food ID
208          155        3

In [61]:
week1sales.head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [62]:
week2.head()

   Customer ID  Food ID
0          688       10
1          813        7
2          495       10
3          189        5
4          267        3

In [63]:
week1sales.merge(week2,how="inner",on=["Customer ID","Food ID"])

   Customer ID  Food ID
0          304        3
1          540        3
2          937       10
3          233        3
4           21        4
5          922        1
6           21        4
7          578        5
8          578        5

In [64]:
condition_one=week1sales["Customer ID"] == 578
condition_two=week1sales["Food ID"] == 5
week1sales[condition_one&condition_two]

     Customer ID  Food ID
224          578        5

In [65]:
condition_one=week2["Customer ID"] == 578
condition_two=week2["Food ID"] == 5
week2[condition_one&condition_two]

     Customer ID  Food ID
29           578        5
189          578        5

In [66]:
#Outer Joins

In [67]:
week1sales.merge(week2,how="outer",on="Customer ID")

     Customer ID  Food ID_x  Food ID_y
0              3        2.0        NaN
1              8        NaN        6.0
2             10        2.0        NaN
3             13        NaN        2.0
4             20        1.0        NaN
..           ...        ...        ...
449          985        5.0        NaN
450          991        2.0        NaN
451          994        NaN        2.0
452          996        NaN       10.0
453         1000        2.0        NaN

[454 rows x 3 columns]

In [68]:
week1sales.merge(week2,how="outer",on="Customer ID",suffixes=["-week1","-week2"])

     Customer ID  Food ID-week1  Food ID-week2
0              3            2.0            NaN
1              8            NaN            6.0
2             10            2.0            NaN
3             13            NaN            2.0
4             20            1.0            NaN
..           ...            ...            ...
449          985            5.0            NaN
450          991            2.0            NaN
451          994            NaN            2.0
452          996            NaN           10.0
453         1000            2.0            NaN

[454 rows x 3 columns]

In [69]:
week1sales.merge(week2,how="outer",on="Customer ID",suffixes=["-week1","-week2"],indicator=True)

     Customer ID  Food ID-week1  Food ID-week2      _merge
0              3            2.0            NaN   left_only
1              8            NaN            6.0  right_only
2             10            2.0            NaN   left_only
3             13            NaN            2.0  right_only
4             20            1.0            NaN   left_only
..           ...            ...            ...         ...
449          985            5.0            NaN   left_only
450          991            2.0            NaN   left_only
451          994            NaN            2.0  right_only
452          996            NaN           10.0  right_only
453         1000            2.0            NaN   left_only

[454 rows x 4 columns]

In [70]:
week2.merge(week1sales,how="outer",on="Customer ID",suffixes=["-week1","-week2"])

     Customer ID  Food ID-week1  Food ID-week2
0              3            NaN            2.0
1              8            6.0            NaN
2             10            NaN            2.0
3             13            2.0            NaN
4             20            NaN            1.0
..           ...            ...            ...
449          985            NaN            5.0
450          991            NaN            2.0
451          994            2.0            NaN
452          996           10.0            NaN
453         1000            NaN            2.0

[454 rows x 3 columns]

In [71]:
week2.merge(week1sales,how="outer",on="Customer ID",suffixes=["-week1","-week2"],indicator=True)

     Customer ID  Food ID-week1  Food ID-week2      _merge
0              3            NaN            2.0  right_only
1              8            6.0            NaN   left_only
2             10            NaN            2.0  right_only
3             13            2.0            NaN   left_only
4             20            NaN            1.0  right_only
..           ...            ...            ...         ...
449          985            NaN            5.0  right_only
450          991            NaN            2.0  right_only
451          994            2.0            NaN   left_only
452          996           10.0            NaN   left_only
453         1000            NaN            2.0  right_only

[454 rows x 4 columns]

In [72]:
merged=week1sales.merge(week2,how="outer",on="Customer ID",suffixes=["-week1","-week2"],indicator="True")
merged["_merge"].value_counts()
merged[merged["_merge"].isin(["left_only","right_only"])]

KeyError: '_merge'

In [73]:
food=pd.read_csv (r"C:\Users\anany\Downloads\foods.csv",index_col="Food ID")
week2=pd.read_csv (r"C:\Users\anany\Downloads\restaurant_week_2_sales.csv")
week1sales= pd.read_csv(r"C:\Users\anany\Downloads\restaurant_week_1_sales.csv")
customer=pd.read_csv (r"C:\Users\anany\Downloads\restaurant_customers.csv",index_col="ID")

ValueError: Index Food ID invalid